### ISSUE TITLE
P100 Login issue

### ISSUE THREAD

**Issue by mmttim** [cwakefie27/TapoConnect#2]
It seems that there was a change to the login API with the latest firmware update. I have 28 P100 devices here, 11 of them have the current firmware and I can't login anymore. Does someone else have the problem?

Other projects seems to have the same problem: https://github.com/petretiandrea/plugp100/issues/113

**Comment by cwakefie27** [comment]
There has been a change, it appears to more than just the login API. I will look into what it takes to migrate to the new one since the work has already been done on a python version of the API. I have not tested it yet, but, when I get the chance I will see if it works and then migrate it to C#. All of my lights are on a proxy offline network so none have updated to the new firmware yet but thanks for bringing this to my attention.

**Comment by mmttim** [comment]
The Python module from my initial post works. I tested it and create a janky workaround. That should make it a bit more easy to copy the fix from there.

**Comment by cwakefie27** [comment]
Okay. I got that library migrated into c# but the code still needs some work to be production ready. I think I should have it within the new few days. As soon as I finish it there will be a new release and likely some minor breaking changes to the API. Thanks for pointing this out and the git reference.

**Comment by cwakefie27** [comment]
Okay. No breaking changes to the API and I did some minor testing on both types of protocols. The login method by default will first try KLAP and if that fails it will fall back to the secure pass-through protocol. You can specify which protocols to use and which order to try them in the constructor for DeviceClient.
