### ISSUE TITLE
Does this support device control through cloud

### ISSUE THREAD

**Issue by owaits** [cwakefie27/TapoConnect#3]
As far as I can tell this library only supports device control on the local network and does not support passthrough control using the app server. Firstly is this correct or am I missing someone. Secondly if I was to add this and provide a PR would you be interested in adding this support?

My particular application does not allow for local control and so I require the passthrough. As far as I can see this is the closest library on GitHub in C# to support this capability it just does not provide the methods to talk to the app server.

**Comment by cwakefie27** [comment]
The way this library works is by connecting to the cloud to get the mac address of the device and then ARP'ing that for the IP address on the local network. All requests are sent directly to the device from the application. 

With that being said, if there is server control available through Tapo, which I would not be surprised as my phone allows me to change the lights state when I am not home, then it would need to be implemented. The starting point would be:

1. Find another library that implements this.
2. Find the Tapo API documentation. 
3. Monitor the traffic from your phone app to the server when not on the same network. 

I would not mind assisting with this if you have questions, but I don't need this functionality.

**Comment by owaits** [comment]
My understanding is that you can use the API server URL and send it the same messages you would send locally but wrap it in a passthrough packet. I am taking a look, if I get something working I will put up a PR. It will fit nicely into your library as its just another device protocol type.

**Comment by cwakefie27** [comment]
The "secure passthrough" is part of the communication protocol that happens when sending to local devices. All messages are encrypted with public / private key and sent through the securePassthrough method. Just looking at the request body, it does not have the mac / IP or ID of the light, so, sending it to the AWS Tapo server it would not know what device to change. To login to the cloud use 

POST https://eu-wap.tplinkcloud.com/
`{
    "method": "login",
    "params": {
        "appType": "Tapo_Android",
        "cloudUserName": "<username>",
        "cloudPassword": "<Password>",
        "terminalUUID": "e01bf1ce-a068-4fbe-8e5d-8957d73e696f"
    }
}`

Then take the token from result.token and use it to list devices with:

POST https://eu-wap.tplinkcloud.com/?token=<result.token>
`{
    "method": "getDeviceList"
}`

These are the only cloud methods I know but if you want to try sending it a secure passthrough you can.
